### ISSUE TITLE
App resets to start screen from configuration pages when switching between apps

### ISSUE THREAD

**Issue by Hibbie89** [martinstoeckli/SilentNotes#192] opened 2022-10-25 12:27 UTC
**Describe the bug**
I just installed the app and wanted to sync the notes via mailbox.org. Therefore, I tried to copy&paste the WebDAV address from the help into the according field, however, the app was reset to the starting screen. So I opened the configuration again, pasted the previously copied information, which worked. Nevertheless, I use a password manager for my passwords, so naturally I tried to fill in the information fom this manager, but it opened the manager app for authentification, and when returning to SilentNotes, it was again on the starting screen.

So when you have to cpy&paste more than one informaton in the configuration process, this is not possible right now.

(btw, the same happened when trying to set the vault password via the password manager or open the vault, when the password manager is locked. However there one could copy the password previously and past it after opening the configuration page)

**Platform (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by martinstoeckli** [comment] 2022-10-25 12:56
Yes this is really inconvenient, I know about this problem, thank you for reporting.

**Comment by liesbe** [comment] 2023-05-02 19:29
Maybe this is related?
Is it intended behaviour that the app (on Android) always jumps to the top of the note again, when I temporarily switched focus to another app? I always have to scroll back to the location where I was writing. Is there a way for me to avoid this?

**Comment by martinstoeckli** [comment] 2023-05-02 20:08
@liesbe It looks like a similar problem, but actually a solution would be a little different. In the first case the routing/navigation is the problem, Android just restarts/resumes the app and it is the responsibility of the app to remember the page it was before. To restore the last position in a note, as we are used to from browsers would require to get the current top row of the editor, and reapply it after a restart. I would have to do some research whether/how this can be done.

Currently I'm playing around with Blazor-WASM, and I think about switching to this technology. It offers another way of routing thus I postponed this issue, until I'm sure which way to go.

**Comment by martinstoeckli** [comment] 2023-09-16 10:18
This issue will be addressed in the upcoming version 8.0.

**Closed** 2024-07-24 09:48 UTC
Labels: bug
