### ISSUE TITLE
Windows version exe/msi download (not ms-appinstaller)

### ISSUE THREAD

**Issue by gitoss** [martinstoeckli/SilentNotes#41] opened 2020-01-08 13:41 UTC
It would be splendid if there'd be an option to get SlentNotes on Windows without using the Microsoft store - it's deactivated on my box, and I can only use a regular exe/msi version.

If it's less comfortable fine, it would be nice to just get it running. My other open source software is managed and updated with chocolatey - for this, it's nice to have an exe/msi version on the github release page.

PS: Being vegan is better than being vegitarian everything considered :-) https://www.martinstoeckli.ch/misc/aboutme_de.html

Thanks for the great app, I'd really like to use it, but need the Windows sync.

**Comment by martinstoeckli** [comment] 2020-01-08 16:41
To have an msi installer would indeed be a fine thing, and I already did some research on this topic. The problem is that the current app is an UWP application and it seems that those cannot be packed into an msi, I would have to build and maintain a completely new project on a new (old) platform, like WinForms or WPF.

On the other side, it would help spreading the tool and to make it known, at the moment it can barely be found. I haven't made up my mind yet, maybe I give it a try, or I wait for DotNet5 to come out.

Is there a reason you can't install it from SilentNotes homepage?

**Comment by gitoss** [comment] 2020-01-10 10:36
Um, the SilentNotes homepage https://www.martinstoeckli.ch/silentnotes/silentnotes.html#download with "Latest Windows version: Install from this site✱✱" has a link to ms-appinstaller:?source=https://www.martinstoeckli.ch/silentnotes/wininstall/SilentNotes.UWP.appinstaller

Firefox states: "The address wasn’t understood. Firefox doesn’t know how to open this address, because one of the following protocols (ms-appinstaller) isn’t associated with any program or is not allowed in this context. You might need to install other software to open this address."

But behold! After looking into the .appinstaller xml file, I can download and install the .appxbundle and .appx manually. Just enable developer mode, put the certificate in " "Trusted Root Certification Authorities", install the 4x files with elevated Powershell Add-AppxPackage ... simple as that :-\

**Comment by martinstoeckli** [comment] 2020-01-10 11:19
The AppInstaller is part of any recent Windows10 version, or it can be downloaded from the Microsoft store, which in your case is not an option of course. It supports automatic updates. You can download the appx manually, but it would be interesting to know whether the auto update will still work.

**Comment by gitoss** [comment] 2020-01-10 17:49
Well, can't help you there as the MS Store doesn't work for me :-\

I can update SilentNotes manually for the time being, but having an msi installer for chocolatey would be nice, too. 

I know the appeal of the MS ecosystem _if_ you stay inside it, I used to develop C++ for Office Addons and am/was a MCP. But SilentNotes is the only UWP app I'd consider, I am using the excellent Joplin for everything else apart from quick post-it notes.

**Comment by martinstoeckli** [comment] 2020-01-11 11:49
I see, if somebody is daring enough to install an UWP app manually, (s)he is surely not the avarage user 😀

The reason why I switched to UWP was that the redirecting after an OAuth2 login in the external browser (One-Drive, Google-Drive). It seems not possible to catch the redirect from a "normal" application, either you need a redirect URL with a random port which cannot be registered in the cloud service, or you need admin privileges to register the custom URN.

The app is compiled requiring Windows10, so I'm not sure if manually installing it on another version works. With a recent Windows10 version the installation should work, even if the AppStore is not available, the auto update is then connected to the version on the homepage, not the app store.

**Comment by martinstoeckli** [comment] 2020-01-21 08:19
I still didn't find a solution for the redirecting problem on the WinForms/WPF platform. I will close the issue for the moment, though I will recheck with outcoming DotNet 5.

**Closed by martinstoeckli** 2020-01-21 08:19 UTC

**Comment by martinstoeckli** [comment] 2020-04-14 19:19
Wanted to inform you, that I found a way to publish the AppxBundle on SilentNotes homepage. It is identical to the one you get from the store, so there is no need to install the developer certificate before. You can find it in the section [sideloading](https://www.martinstoeckli.ch/silentnotes/silentnotes.html#sideloading).
