### ISSUE TITLE
can not remember position and size.  version 8.0.1 for windows 10

### ISSUE THREAD

**Issue by mlc2743** [martinstoeckli/SilentNotes#259] opened 2024-07-31 11:34 UTC
Silentnotes remembered the [position] and [size] before 8.0 and I'm used to the size like it for mobile phone.  
But v8.0 it always reset the position and size. Unpleasant feelings.

**Comment by martinstoeckli** [comment] 2024-07-31 20:59
Thank you for writing. I close this issue because it is a duplicate of #255 .

**Closed by martinstoeckli** 2024-07-31 20:59 UTC
Labels: enhancement
